# Generated by Django 5.0.3 on 2024-03-21 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('color1', models.CharField(max_length=100)),
                ('color2', models.CharField(max_length=100)),
            ],
        ),
    ]
