# Generated by Django 5.0.3 on 2024-03-21 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0002_time_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='branding',
            field=models.ImageField(blank=True, null=True, upload_to='chess/'),
        ),
    ]
